### ISSUE TITLE
Bledom device not working

### ISSUE THREAD

**Issue by Majikmonke** [dave-code-ruiz/elkbledom#62]
Hi 

I am unable to add 2 devices to this integration. I can connect to both through phone app Lotus Lantern and can see MAC codes but get an error when trying to connect stating unable to connect to Elkbledom
![Screenshot_20240209_211939_Home Assistant](https://github.com/dave-code-ruiz/elkbledom/assets/151208588/a2c4a316-ed7d-4a7c-a4d6-a4e1c361a006)
![Screenshot_20240209_211739_Lotus Lantern](https://github.com/dave-code-ruiz/elkbledom/assets/151208588/d95e42d2-91a8-4411-b555-b7822f319548)

**Comment by hbkhalil** [comment]
I have the same issue

**Comment by dave-code-ruiz** [comment]
Ok, first you need to know that bluetooth only support one client connected to strip, you need to disconnect your strip from your app first to connect it with HA in your pic there are a button (like a chain) right to the ELKBLE strip click it to connect/disconnect strip.

Now you can enable debug mode:
https://github.com/dave-code-ruiz/elkbledom?tab=readme-ov-file#enable-debug-mode

And you can send me debug logs to know exact error you receive.

thanks

**Comment by hbkhalil** [comment]
Ok I tried to unlink it but I still get the same issue.
I tried to get the debug mode, but I don't think it is working. I think there is an issue with my Bluetooth adapter.
This what I am getting

________________________________

**Comment by hbkhalil** [comment]
Logger: bluetooth_auto_recovery.recover
Source: config_entries.py:444
First occurred: 12:37:54 (55 occurrences)
Last logged: 13:15:15

  *   Could not determine the power state of the Bluetooth adapter hci0 [00:00:00:00:00:00] due to timeout after 5 seconds
  *   Bluetooth adapter hci0 [00:00:00:00:00:00] could not be reset:

________________________________

**Comment by Majikmonke** [comment]
Hi

Still unable to connect with link broken

Can get past the connection screen to enable debugging.

Kind regards

Dan Scate

Sent from my Samsung Galaxy smartphone.



-------- Original message --------
From: hbkhalil ***@***.***>
Date: 26/02/2024 13:17 (GMT+00:00)
To: dave-code-ruiz/elkbledom ***@***.***>
Cc: Majikmonke ***@***.***>, Author ***@***.***>
Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62)


Logger: bluetooth_auto_recovery.recover
Source: config_entries.py:444
First occurred: 12:37:54 (55 occurrences)
Last logged: 13:15:15

* Could not determine the power state of the Bluetooth adapter hci0 [00:00:00:00:00:00] due to timeout after 5 seconds
* Bluetooth adapter hci0 [00:00:00:00:00:00] could not be reset:

________________________________

**Comment by hbkhalil** [comment]
No I can't even add the integration Ibrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton.
-------- Original message --------From: Majikmonke ***@***.***> Date: 27/02/2024  09:52  (GMT+00:00) To: dave-code-ruiz/elkbledom ***@***.***> Cc: hbkhalil ***@***.***>, Comment ***@***.***> Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62) 
Hi



Still unable to connect with link broken



Can get past the connection screen to enable debugging.



Kind regards



Dan Scate



Sent from my Samsung Galaxy smartphone.







-------- Original message --------

From: hbkhalil ***@***.***>

Date: 26/02/2024 13:17 (GMT+00:00)

To: dave-code-ruiz/elkbledom ***@***.***>

Cc: Majikmonke ***@***.***>, Author ***@***.***>

Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62)





Logger: bluetooth_auto_recovery.recover

Source: config_entries.py:444

First occurred: 12:37:54 (55 occurrences)

Last logged: 13:15:15



* Could not determine the power state of the Bluetooth adapter hci0 [00:00:00:00:00:00] due to timeout after 5 seconds

* Bluetooth adapter hci0 [00:00:00:00:00:00] could not be reset:



________________________________

From: Ibrahim Harrane ***@***.***>

Sent: 26 February 2024 13:16

To: dave-code-ruiz/elkbledom ***@***.***>

Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62)



Ok I tried to unlink it but I still get the same issue.

I tried to get the debug mode, but I don't think it is working. I think there is an issue with my Bluetooth adapter.

This what I am getting



________________________________

From: Dave Code ***@***.***>

Sent: 26 February 2024 07:55

To: dave-code-ruiz/elkbledom ***@***.***>

Cc: hbkhalil ***@***.***>; Comment ***@***.***>

Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62)





Ok, first you need to know that bluetooth only support one client connected to strip, you need to disconnect your strip from your app first to connect it with HA in your pic there are a button (like a chain) right to the ELKBLE strip click it to connect/disconnect strip.



Now you can enable debug mode:

https://github.com/dave-code-ruiz/elkbledom?tab=readme-ov-file#enable-debug-mode



And you can send me debug logs to know exact error you receive.



thanks

**Comment by dave-code-ruiz** [comment]
> Could not determine the power state of the Bluetooth adapter hci0 [00:00:00:00:00:00]

Ok, you have problems with your bluetooth adapter , not a integration problem

**Comment by dave-code-ruiz** [comment]
> Can get past the connection screen to enable debugging.

to enable debug mode follow instructions in:

https://github.com/dave-code-ruiz/elkbledom/?tab=readme-ov-file#enable-debug-mode

to show your log depends your system config, if it is docker, rpi, depends your HA version, etc..

I can show my log with:

docker logs -f homeassistant

**Comment by hbkhalil** [comment]
Yes it seems like it. U can close the issueIbrahim El khalil Harrane.Institute of sound and vibration research ISVRUniversity of Southampton.
-------- Original message --------From: Dave Code ***@***.***> Date: 27/02/2024  10:18  (GMT+00:00) To: dave-code-ruiz/elkbledom ***@***.***> Cc: hbkhalil ***@***.***>, Comment ***@***.***> Subject: Re: [dave-code-ruiz/elkbledom] Bledom device not working (Issue #62) 

Could not determine the power state of the Bluetooth adapter hci0 [00:00:00:00:00:00]

Ok, you have problems with your bluetooth adapter , not a integration problem
