### ISSUE TITLE
ESPhome BT proxy compatability 

### ISSUE THREAD

**Issue by iotola** [dave-code-ruiz/elkbledom#70]
I have a Bluetooth adapter directly connected to HA which will connect and control my lamp but it's just too far to work reliably. 
The BT adapter also doesn't always start which can be annoying and requires me to pull the plug.
So I set up an ESPhome BT proxy close to the lamp but this proxy doesn't see the lamp. 

Is an ESPhome BT proxy compatible?

If not does anyone have any suggestions how to solve it?

**Comment by scottcopus** [comment]
I am also interested to know if this works with HA ESPHome BT proxies too.

**Comment by iotola** [comment]
> I am also interested to know if this works with HA ESPHome BT proxies too. If so (or not) can you update the README? Thanks.

Just to confirm it does work with the ESPhome BT proxy. I had a hardware issue.
In my case, the ESPhome BT proxy needs to be quite close to my lamp to maintain/establish a connection quickly, but this might be my ESP32C3 which doesn't seem to have very good BT distance.

**Comment by dave-code-ruiz** [comment]
I dont know nothing about BT proxy, sorry

I use bleak library can you answer in their repo

Rewards

Sorry

**Comment by scottcopus** [comment]
I can also now confirm this project works with ESPHome BT proxies too. But I only have one proxy and one BT LED strip. I don’t know its behavior when you have multiple BT proxies or LEDs. 

@iotola Your connection issues could be related because you chose the ESP32C3. i think that one just has one core meaning Wi-Fi & BT must share it unlike on dual core devices where each has a dedicated core to each protocol. 

@dave-code-ruiz I assume the setting “Disconnect delay” is in seconds? I would suggest adding this to the setting’s title to avoid confusion. 

Thanks for this project! It helped with my light strip!

**Comment by ianmcginley** [comment]
i've got a mix of olimex bt proxies from ESP home and bought some ESP32-S3 from Lonely Binary which require a bit more massaging.

this works great with bluetooth proxies. The big catch is you can only manage 3 devices simultaneously with esphome bt proxies. So, if you are trying to manage multiple lights for whatever reason, try to ensure you have a relevant proxy near your cluster of lights.
